//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOIT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISTRICT()
        {
            this.VDC = new HashSet<VDC>();
        }
    
        public short DISTRICTID { get; set; }
        public short ZONEID { get; set; }
        public string DISTRICTNAME { get; set; }
        public Nullable<int> ProvinenceID { get; set; }
        public string DISTRICTNAME_Nep { get; set; }
        public Nullable<int> OrganizationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VDC> VDC { get; set; }
    }
}
