//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOIT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class experience
    {
        public int id { get; set; }
        public string nameOfEmployer { get; set; }
        public string empStatus { get; set; }
        public string durationFrom { get; set; }
        public string durationTo { get; set; }
        public string tenure { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<bool> status { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
