//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOIT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class familyDetail
    {
        public int id { get; set; }
        public string relationship { get; set; }
        public string name { get; set; }
        public string dob { get; set; }
        public string occupation { get; set; }
        public int employeeId { get; set; }
        public Nullable<bool> status { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public string modifiedDate { get; set; }
        public string deletedBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
