//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOIT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQualification
    {
        public int Id { get; set; }
        public Nullable<int> UserProfileId { get; set; }
        public Nullable<bool> IsEducation { get; set; }
        public Nullable<bool> IsCertification { get; set; }
        public string Title { get; set; }
        public string Institution { get; set; }
        public string ReceiveDate { get; set; }
        public string FilePath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CraetedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
