//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOIT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDC
    {
        public short VDCID { get; set; }
        public short ZONEID { get; set; }
        public short DISTRICTID { get; set; }
        public string VDCNAME { get; set; }
    
        public virtual DISTRICT DISTRICT { get; set; }
    }
}
